1.10 context
studygolang/gctt-godoc pull request #23
Opened 2018-03-03 16:46 UTC by saberuster

翻译完成
替换旧版本pr
#17

2018-03-03 16:50 UTC, saberuster commented
#24

2018-03-04 03:43 UTC, saberuster commented
完成1.10 修改还请校对老哥抽空review。@yesuu

2018-03-04 12:31 UTC, yesuu requested changes

2018-03-04 12:31 UTC, yesuu commented on Translate/context/context.md
> +    // gen generates integers in a separate goroutine and
没有译例子？还有其他同类问题未标出

2018-03-04 12:31 UTC, yesuu commented on Translate/context/context.md
> +为了避免不同的包使用时出现相同的键，key 必须是可比较的并且不能是内置的 string 等类型。 WithValue 的用户应该定义自己的 key 类型。为了避免分配成 interface{]，context 的 key 一般都为具体类型。或者导出的 context 的 key 变量的静态类型应该是一个指针或者接口。
「为了避免分配成 interface{]」，这个灵性的右方括号。

2018-03-04 12:31 UTC, yesuu commented on Translate/context/context.md
> +
多了4个空格。还有其他同类问题未标出

2018-03-06 06:29 UTC, saberuster commented
@yesuu 完成修改还请抽空确认一下，辛苦啦。

2018-03-26 22:06 UTC, yesuu approved these changes

2018-03-26 22:06 UTC, merged